Feature/add toggle which changes the language
TarasMavrovych/teras-mavr-cv pull request #19
Opened 2022-07-05 17:26 UTC by DarkSoulH

2022-07-06 17:04 UTC, PavelSukhinin commented on assets/js/app.js
> +  const localization = document.getElementById("switchlang");
1. don't use anonymous functions for event handling
2. get your checkbox inside handler via event

2022-07-06 17:07 UTC, dissolvent commented on assets/css/style.css
> +  -webkit-appearance: none;
why with webkit prefix?

2022-07-06 17:07 UTC, dissolvent commented on assets/js/app.js
> +  localization?.checked ? window.location.href = 'index_en.html': window.location.href = 'index.html'
1. don't use anonymous functions for event handling
2. get your checkbox inside handler via event

2022-07-06 17:07 UTC, dissolvent commented on assets/js/app.js
> +document.getElementById("switchlang").addEventListener("click", function() {
execute your scripts in strict mode

2022-07-06 17:07 UTC, dissolvent commented on index.html
> +  <main class="main_section" id="ua">
I believe you're not using this id

2022-07-09 11:16 UTC, dissolvent requested changes

2022-07-09 11:16 UTC, dissolvent commented on assets/js/app.js
> +    localization?.checked ? window.location.href = 'index_en.html': window.location.href = 'index.html'
make your handler reusable. 
```suggestion
  function handleClickLang(ev) {
   // ev.something - research this object
   don't use localization?.checked defined in outer scope
```

2022-07-10 08:47 UTC, dissolvent approved these changes

2022-07-10 08:59 UTC, merged